import fs from 'fs';
import { blogPosts } from '../src/data/blogPosts';

const blogPostsMeta = blogPosts.map(post => ({
  id: post.id,
  title: post.title,
  excerpt: post.excerpt,
  imageUrl: post.imageUrl,
  ...(post.imageAlt !== undefined && { imageAlt: post.imageAlt }),
  ...(post.imagePosition !== undefined && { imagePosition: post.imagePosition }),
  ...(post.image !== undefined && { image: post.image }),
  date: post.date,
  publishedAt: post.publishedAt,
  author: post.author,
  ...(post.authorName !== undefined && { authorName: post.authorName }),
  ...(post.authorRole !== undefined && { authorRole: post.authorRole }),
  category: post.category,
}));

const fileContent = `// Auto-generated file. Do not edit manually. Generated by scripts/generate-blog-meta.ts
import { BlogCategory, BlogImage } from './blogPosts';

export interface BlogPostMeta {
  id: string;
  title: string;
  excerpt: string;
  imageUrl: string;
  imageAlt?: string;
  imagePosition?: string;
  image?: BlogImage;
  date: string;
  publishedAt: string;
  author: string;
  authorName?: string;
  authorRole?: string;
  category: BlogCategory;
}

export const blogPostsMeta: BlogPostMeta[] = ${JSON.stringify(blogPostsMeta, null, 2)};
`;

fs.writeFileSync('src/data/blogPostsMeta.ts', fileContent);
console.log('src/data/blogPostsMeta.ts generated successfully!');
