// Auto-generated file. Do not edit manually. Generated by scripts/generate-blog-meta.ts
import { BlogCategory, BlogImage } from './blogPosts';

export interface BlogPostMeta {
  id: string;
  title: string;
  excerpt: string;
  imageUrl: string;
  imageAlt?: string;
  imagePosition?: string;
  image?: BlogImage;
  date: string;
  publishedAt: string;
  author: string;
  authorName?: string;
  authorRole?: string;
  category: BlogCategory;
}

export const blogPostsMeta: BlogPostMeta[] = [
  {
    "id": "pantallas-ninos-cuando-preocuparse",
    "title": "Pantallas y cerebro infantil: qué dice la ciencia y cuándo preocuparse",
    "excerpt": "Por qué cuesta tanto que un niño suelte el móvil y qué está pasando de verdad en su cerebro. Señales para prestar atención y qué hacer en casa.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto,w_1200/mifaro/pantallas-ninos-hero-01",
    "imageAlt": "Niño interactuando con una pantalla en una habitación con iluminación tenue, ilustración sobre el cerebro infantil y las pantallas",
    "imagePosition": "object-[50%_50%]",
    "date": "agosto 2026",
    "publishedAt": "2026-08-05",
    "author": "Equipo Mi Faro",
    "category": "Familias"
  },
  {
    "id": "lucia-creia-que-sin-el-no-iba-a-poder-seguir",
    "title": "Lucía: \"Creía que sin él no iba a poder seguir\"",
    "excerpt": "Lo peor no era cuando se iba. Lo peor era el alivio que sentía cuando volvía. Una historia real sobre dependencia emocional y el camino para volver a sostenerse sola.",
    "imageUrl": "/lucia-turia-hero.jpg",
    "imageAlt": "Retrato de Lucía pensativa sentada en un banco de madera en los Jardines del Turia, Valencia",
    "imagePosition": "object-[50%_50%]",
    "date": "26 de Julio, 2026",
    "publishedAt": "2026-07-26",
    "author": "Equipo Mi Faro",
    "authorName": "Amparo Pons Ferrer",
    "authorRole": "Historia adaptada y escrita por",
    "category": "Las Voces del Faro"
  },
  {
    "id": "ana-el-cauce-y-el-primer-paso",
    "title": "Ana. El cauce y el primer paso.",
    "excerpt": "Llevaba casi un año sabiendo que algo no iba bien. Pero fue la muerte de Felicia, su gata, lo que lo hizo visible de golpe. A veces necesitamos vaciarnos de todo lo que cargamos para encontrar por fin una salida.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto,w_1200/v1783330439/mifaro/ana-el-cauce-y-el-primer-paso-hero.png",
    "imageAlt": "Mujer sentada en un banco mirando el cauce del Turia al atardecer, Valencia",
    "date": "06 de Julio, 2026",
    "publishedAt": "2026-07-06",
    "author": "Equipo Mi Faro",
    "category": "Las Voces del Faro"
  },
  {
    "id": "padres-adolescentes-distancia-miedo-vinculo-valencia",
    "title": "Cuando tu hijo adolescente se aleja y no sabes qué hacer",
    "excerpt": "Hay padres que llegan con un libro de autoayuda bajo el brazo y la sensación de haberlo intentado todo. No vienen a hablar de sí mismos — vienen a hablar de su hijo. Pero lo que aparece enseguida es otra cosa: el miedo, la distancia, la culpa de quien lleva tiempo sosteniendo solo algo que se le escapa de las manos.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto,w_1200/v1782768985/mifaro/padres-adolescentes-distancia-vinculo-mifaro-hero.png",
    "imageAlt": "Puerta de habitación cerrada en casa mediterránea con luz cálida de pasillo",
    "date": "29 de Junio, 2026",
    "publishedAt": "2026-06-29",
    "author": "Equipo Mi Faro",
    "category": "Familias y adolescentes"
  },
  {
    "id": "al-principio-pense-que-era-amor",
    "title": "Al principio pensé que era amor: cuando un vínculo te va borrando",
    "excerpt": "Mayte se alejó de todo su mundo por otro donde no había nada. Y al principio pensó que era amor.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto,w_1200/v1781974884/mifaro/voces-del-faro/voces-mayte-01-apertura.jpg",
    "imageAlt": "Mujer joven de perfil junto a una ventana, luz suave, expresión pensativa",
    "date": "20 de Junio, 2026",
    "publishedAt": "2026-06-20",
    "author": "Equipo Mi Faro",
    "category": "Las Voces del Faro"
  },
  {
    "id": "yo-no-consumia-para-escapar",
    "title": "No consumía para escapar. Consumía para rendir.",
    "excerpt": "Andrés tenía empresa, familia y todo bajo control por fuera. Por eso tardó años en pedir ayuda.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto,w_1200/v1781974879/mifaro/voces-del-faro/voces-andres-01-apertura.jpg",
    "imageAlt": "Hombre de perfil junto a una ventana de oficina al atardecer, luz cálida",
    "date": "20 de Junio, 2026",
    "publishedAt": "2026-06-20",
    "author": "Equipo Mi Faro",
    "category": "Las Voces del Faro"
  },
  {
    "id": "paula-y-marcos-el-silencio",
    "title": "Paula y Marcos: lo que veían en el otro, lo tenían ellos",
    "excerpt": "Once años juntos, no discuten. Pero los dos duermen mal y sienten que algo se rompió sin saber cuándo.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto,w_1200/v1781974875/mifaro/voces-del-faro/voces-paula-marcos-01-apertura.jpg",
    "imageAlt": "Pareja sentada en un sofá en silencio, luz cálida de interior, distancia entre ambos",
    "date": "20 de Junio, 2026",
    "publishedAt": "2026-06-20",
    "author": "Equipo Mi Faro",
    "category": "Las Voces del Faro"
  },
  {
    "id": "sergio-las-3-15",
    "title": "Sergio y las 3:15",
    "excerpt": "Se despierta a las 3:15. Sabe que debería levantarse y no se mueve. De día funciona bien. De noche no.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto,w_1200/v1781974870/mifaro/voces-del-faro/voces-sergio-01-apertura.jpg",
    "imageAlt": "Habitación a oscuras de madrugada con luz tenue entrando por la ventana",
    "date": "20 de Junio, 2026",
    "publishedAt": "2026-06-20",
    "author": "Equipo Mi Faro",
    "category": "Las Voces del Faro"
  },
  {
    "id": "maria-perdi-a-mi-nino",
    "title": "María no vino a hablar de su hijo. Vino a hacer el duelo de su niño.",
    "excerpt": "Nico sigue en casa. Pero el niño que corría a contarle todo ya no está. Y nadie te dice cómo se llora eso.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto,w_1200/v1781973637/mifaro/voces-del-faro/voces-maria-01-apertura.jpg",
    "imageAlt": "Madre mirando por la ventana en un interior cálido, luz suave, de perfil",
    "date": "20 de Junio, 2026",
    "publishedAt": "2026-06-20",
    "author": "Equipo Mi Faro",
    "category": "Las Voces del Faro"
  },
  {
    "id": "laura-cuando-ya-no-puedo-mas",
    "title": "Cuando ya no puedo más: la familia que sostuvo demasiado",
    "excerpt": "Laura vino a hablar de su marido. Tardó veinte minutos en darse cuenta de que venía a hablar de ella.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto,w_1200/v1781973632/mifaro/voces-del-faro/voces-laura-01-apertura.png",
    "imageAlt": "Mujer junto a una ventana en luz tenue, de perfil, interior cálido",
    "date": "20 de Junio, 2026",
    "publishedAt": "2026-06-20",
    "author": "Equipo Mi Faro",
    "category": "Las Voces del Faro"
  },
  {
    "id": "familias-adicciones-valencia-como-acompanar-sin-destruirse",
    "title": "Familias y adicciones en Valencia: lo que también les pasa · Mi Faro",
    "excerpt": "La adicción no es solo el problema de quien consume. Es el problema de todos los que le quieren. Esto es lo que le pasa a la familia, y lo que se puede hacer.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto,w_1200/v1781599154/mifaro/familias-adicciones-valencia-hero.png",
    "imageAlt": "Mujer tomando la decisión de pedir ayuda por la adicción de un familiar · Mi Faro Valencia",
    "date": "16 de Junio, 2026",
    "publishedAt": "2026-06-16",
    "author": "Equipo Mi Faro",
    "category": "Adicciones y familia"
  },
  {
    "id": "sintomas-fisicos-estres-emocional-ansiedad-valencia",
    "title": "Me dicen que estoy bien, pero no me siento bien: síntomas físicos de ansiedad en Valencia",
    "excerpt": "Hay personas que van al médico, se hacen pruebas y escuchan que todo está bien, pero siguen sin encontrarse bien. Mareos, tensión, insomnio, digestiones difíciles o presión en el pecho pueden ser formas en las que el cuerpo expresa un malestar que todavía no encuentra palabras.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1779830106/mifaro/estres-emocional-ansiedad-valencia_VLR9Xr3x.png",
    "date": "26 de Mayo, 2026",
    "publishedAt": "2026-05-26",
    "author": "Equipo Mi Faro",
    "category": "Ansiedad y malestar"
  },
  {
    "id": "burnout-silencioso-agotamiento-emocional-valencia",
    "title": "Burnout silencioso en Valencia: cuando sigues funcionando pero por dentro ya no puedes más",
    "excerpt": "El 87% de los profesionales en España reconoce haberlo experimentado sin decírselo a nadie. No hay baja médica ni crisis visible. Solo una sensación creciente de que algo se ha apagado por dentro.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1779830168/mifaro/Estres_laboral_bornout_valencia_vZGFrTsv.png",
    "date": "18 de Mayo, 2026",
    "publishedAt": "2026-05-18",
    "author": "Amparo Pons Ferrer",
    "category": "Ansiedad y malestar"
  },
  {
    "id": "problemas-de-pareja-valencia",
    "title": "¿Cuándo ir a terapia de pareja en Valencia? Lo que nadie te dice antes de decidir",
    "excerpt": "Hay parejas que llegan a consulta después de años de espera. Y hay parejas que llegan antes - cuando todavía hay margen para trabajar. Las segundas casi siempre lo saben. La pregunta es cuándo dar ese paso.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1779830090/mifaro/Terapia_de_pareja_valencia_L8vhbQdR.png",
    "date": "15 de Mayo, 2026",
    "publishedAt": "2026-05-15",
    "author": "Equipo Mi Faro",
    "category": "Terapia familiar"
  },
  {
    "id": "violencia-filio-parental-hijos-que-agreden-padres-valencia",
    "title": "Cuando tu hijo o hija te hace daño: lo que pocas familias se atreven a contar",
    "excerpt": "Hay padres y madres que llevan meses, o años, viviendo con miedo dentro de su propia casa. Y lo primero que sienten, antes de nombrar lo que pasa, es vergüenza. La violencia filio-parental es un problema que tiene nombre, pero que pocas familias pronuncian.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1779830151/mifaro/Violencia_familiar_portada_nLYWYwdz.png",
    "date": "15 de Mayo, 2026",
    "publishedAt": "2026-05-15",
    "author": "Ale Garcia",
    "category": "Terapia familiar"
  },
  {
    "id": "burnout-valencia-40-por-ciento",
    "title": "Valencia, 40% de burnout: cómo se ve desde dentro",
    "excerpt": "Cuatro de cada diez trabajadores en Valencia tienen burnout. La mayoría sigue funcionando. Eso es exactamente el problema.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1779830097/mifaro/Estres-laboral-burnout-valencia_Qdydd6cV.png",
    "date": "11 de Mayo, 2026",
    "publishedAt": "2026-05-11",
    "author": "Equipo Mi Faro",
    "category": "Orientación"
  },
  {
    "id": "duelo-perdida-dolor-que-no-pasa-valencia",
    "title": "El duelo que nadie ve: cuando el dolor no es solo por la muerte",
    "excerpt": "Hay personas que cargan con un peso que no saben cómo explicar. Una tristeza que no encuentra destinatario. Un dolor que no tiene certificado. Porque el duelo no siempre llega de la forma en que lo reconocemos.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1779830085/mifaro/psicologo-Duelo-valencia_Hxkkw8d0.png",
    "date": "11 de Mayo, 2026",
    "publishedAt": "2026-05-11",
    "author": "Equipo Mi Faro",
    "category": "Orientación"
  },
  {
    "id": "adiccion-movil-adolescentes-valencia",
    "title": "Mi hijo no puede dejar el móvil: lo que hay debajo del uso compulsivo de la pantalla",
    "excerpt": "Quitarle el teléfono o poner límites puede no ser suficiente cuando el móvil está cumpliendo una función más profunda. Este artículo es para madres y padres que sienten que algo está pasando, pero no saben cómo nombrarlo.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1779830075/mifaro/adolescentes_y_movil_valencia_CMcbJdbt.png",
    "date": "9 de Mayo, 2026",
    "publishedAt": "2026-05-09",
    "author": "Equipo Mi Faro",
    "category": "Familias y adolescentes"
  },
  {
    "id": "ansiedad-en-el-trabajo-valencia",
    "title": "Ansiedad en el trabajo: cuándo pedir ayuda antes de llegar a la baja",
    "excerpt": "Hay personas que no están de baja, pero tampoco están bien. Funcionan, cumplen y responden, pero por dentro algo lleva tiempo sin ir bien. Este artículo es para quien empieza a notarlo.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1779830131/mifaro/ansiedad-en-el-trabajo-valencia_gcg34r31.png",
    "date": "8 de Mayo, 2026",
    "publishedAt": "2026-05-08",
    "author": "Equipo Mi Faro",
    "category": "Ansiedad y malestar"
  },
  {
    "id": "estres-laboral-burnout-valencia",
    "title": "Estrés laboral y burnout en Valencia: cuando el trabajo deja de ser saludable",
    "excerpt": "Hay un cansancio que no se va con el fin de semana. Que no mejora con vacaciones. Que ya no sabe de lunes ni de viernes. Este artículo es para quien lleva tiempo así y todavía no sabe cómo llamarlo.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1779830078/mifaro/Bornout-estres-laboral_DZdb1gkc.png",
    "date": "6 de Mayo, 2026",
    "publishedAt": "2026-05-06",
    "author": "Equipo Mi Faro",
    "category": "Ansiedad y malestar"
  },
  {
    "id": "no-puedo-dormir-preocupaciones-valencia",
    "title": "No puedo dormir por las preocupaciones: qué está pasando y qué se puede hacer",
    "excerpt": "Dar vueltas a los mismos pensamientos cuando la luz se apaga. No poder descansar aunque estés agotado. Entender por qué pasa y cuándo tiene sentido buscar ayuda psicológica en Valencia.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1779830081/mifaro/no-puedo-dormir-preocupaciones-valencia_Fzfxjdpm.jpg",
    "date": "28 de Abril, 2026",
    "publishedAt": "2026-04-28",
    "author": "Ale Garcia",
    "category": "Ansiedad y malestar"
  },
  {
    "id": "ansiedad-por-la-noche-valencia",
    "title": "Ansiedad nocturna en Valencia: cuando la noche deja de ser descanso",
    "excerpt": "Hay personas que funcionan durante el día y se desmoronan por la noche. No es debilidad ni exageración: es el momento en que el cuerpo ya no puede seguir posponiendo lo que lleva horas callado.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1780774678/mifaro/ansiedad-nocturna-valencia-hero-mifaro.png",
    "date": "4 de Mayo, 2026",
    "publishedAt": "2026-05-04",
    "author": "Equipo Mi Faro",
    "category": "Ansiedad y malestar"
  },
  {
    "id": "cuando-lo-que-preocupa-no-se-puede-nombrar",
    "title": "Cuando algo no va bien pero no sabes cómo llamarlo: el malestar que no tiene nombre todavía",
    "excerpt": "No siempre hace falta un diagnóstico para saber que algo no funciona. Hay un malestar que no cabe en ninguna categoría pero que pesa igual. Este artículo es para quien está en ese lugar.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1779830057/mifaro/Adicciones_269wbF4H.jpg",
    "date": "10 de Abril, 2026",
    "publishedAt": "2026-04-10",
    "author": "Equipo Mi Faro",
    "category": "Ansiedad y malestar"
  },
  {
    "id": "relaciones-toxicas-desgaste-emocional",
    "title": "Relaciones que desgastan: cuando querer a alguien te hace daño",
    "excerpt": "No todas las relaciones dañinas son dramáticas. Algunas simplemente consumen, poco a poco, sin que nadie pueda señalar el momento exacto en que algo empezó a ir mal. Este artículo es para quien empieza a notarlo.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1779830124/mifaro/Terapia_de_pareja_3_bwLdBC7K.jpg",
    "date": "10 de Abril, 2026",
    "publishedAt": "2026-04-10",
    "author": "Equipo Mi Faro",
    "category": "Vínculos y pareja"
  },
  {
    "id": "tratamiento-ambulatorio-adicciones-valencia",
    "title": "Tratamiento ambulatorio de adicciones en Valencia: qué es, cómo funciona y cuándo planteárselo",
    "excerpt": "Muchas personas retrasan pedir ayuda porque creen que tratar una adicción implica ingresar. Pero no siempre es así. Una guía clara para entender qué es el tratamiento ambulatorio en Valencia y cuándo puede tener sentido.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1779830121/mifaro/Adicciones-valencia_bvTvqrkz.png",
    "date": "05 de Abril, 2026",
    "publishedAt": "2026-04-05",
    "author": "Equipo Mi Faro",
    "category": "Orientación"
  },
  {
    "id": "ansiedad-cronica-valencia",
    "title": "Vivir en alerta constante: cuando el cuerpo lleva años diciéndote algo que todavía no has escuchado",
    "excerpt": "No siempre se llama ansiedad. A veces se llama no poder descansar, estar siempre pendiente de algo o sentir que nunca terminas de bajar la guardia. Este artículo es para quien lleva tiempo así.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1779830125/mifaro/ansiedad_dtNVhL79.jpg",
    "date": "05 de Abril, 2026",
    "publishedAt": "2026-04-05",
    "author": "Equipo Mi Faro",
    "category": "Ansiedad y malestar"
  },
  {
    "id": "codependencia-que-es-familias-adicciones-valencia",
    "title": "Qué es la codependencia, cuando ayudar al otro te rompe a ti",
    "excerpt": "Hay personas que llevan años volcadas en el problema de otro. Que han dejado de vivir su propia vida sin darse cuenta. Que ya no saben muy bien dónde terminan ellas y dónde empieza el otro. A eso se le llama codependencia.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1779830136/mifaro/codependencia_hvyMF9CR.png",
    "date": "05 de Abril, 2026",
    "publishedAt": "2026-04-05",
    "author": "Equipo Mi Faro",
    "category": "Adicciones y familia"
  },
  {
    "id": "psicologo-online-valencia-que-cambia-que-no",
    "title": "Psicólogo online en Valencia: qué cambia, qué no cambia y cómo saber si es lo que necesitas",
    "excerpt": "La terapia online no es una versión menor de la presencial. Es un formato distinto, con sus propias ventajas y sus propias limitaciones. Aquí explicamos qué cambia y qué no, para que puedas decidir con más información.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1779830173/mifaro/Psicologo_valencia_online_zB2jbSns.jpg",
    "date": "06 de Abril, 2026",
    "publishedAt": "2026-04-06",
    "author": "Equipo Mi Faro",
    "category": "Ansiedad y malestar"
  },
  {
    "id": "consumo-pareja-confusion-identidad-drogas",
    "title": "Ya no sé si es él o es lo que consume: la confusión de querer a alguien que se borra a ratos",
    "excerpt": "No es que esté enganchado. No ha tocado fondo. Sigue yendo al trabajo y quedando con los amigos. Pero tú llevas tiempo sin saber muy bien con quién estás cuando llega a casa. Eso también tiene nombre.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1779830179/mifaro/Pareja-adicciones_zG9zFM2H.png",
    "date": "07 de Abril, 2026",
    "publishedAt": "2026-04-07",
    "author": "Equipo Mi Faro",
    "category": "Adicciones y familia"
  },
  {
    "id": "terapia-pareja-valencia-cuando-tiene-sentido",
    "title": "No hace falta que todo esté roto para ir a terapia de pareja: cuándo tiene sentido antes de llegar al límite",
    "excerpt": "Hay parejas que no discuten apenas, que no tienen una crisis declarada, que desde fuera parecen estar bien. Y que por dentro llevan tiempo con la sensación de que algo se ha perdido sin saber muy bien cuándo. Para esas parejas también existe la terapia.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1779830138/mifaro/Psicologo_valencia_j53XwQzB.jpg",
    "date": "07 de Abril, 2026",
    "publishedAt": "2026-04-07",
    "author": "Equipo Mi Faro",
    "category": "Terapia de pareja y vínculos"
  },
  {
    "id": "ansiedad-consumo-drogas-alcohol-valencia",
    "title": "Ansiedad y consumo: por qué van tan juntos, por qué nadie lo dice y qué se puede hacer",
    "excerpt": "No siempre se empieza a consumir porque sí. A veces se empieza porque algo duele y esto funciona, al menos un rato. El problema es lo que pasa después. Y la relación entre ansiedad y consumo es más frecuente, más silenciosa y más tratable de lo que parece.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1779830113/mifaro/Ansiedad-valencia_XvvV3C1q.jpg",
    "date": "07 de Abril, 2026",
    "publishedAt": "2026-04-07",
    "author": "Equipo Mi Faro",
    "category": "Ansiedad y malestar"
  },
  {
    "id": "rol-familia-proceso-terapeutico",
    "title": "El rol de la familia en el proceso terapéutico: por qué el entorno es la clave del cambio",
    "excerpt": "La familia no es un decorado en la recuperación; es una pieza fundamental. Analizamos cómo influye el entorno afectivo en el proceso y cómo acompañar sin invadir.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1779830096/mifaro/Adicciones_valencia_PrkmQrvt.jpg",
    "date": "08 de Abril, 2026",
    "publishedAt": "2026-04-08",
    "author": "Equipo Mi Faro",
    "category": "Terapia familiar"
  },
  {
    "id": "terapia-pareja-valencia-cuando-hablar-ya-no-alcanza",
    "title": "Terapia de pareja en Valencia: cuando hablar ya no alcanza",
    "excerpt": "Hay relaciones en las que el problema no es solo discutir, sino haber perdido la forma de escucharse. Señales, preguntas y claves para saber cuándo la terapia de pareja en Valencia puede ayudar.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1779830179/mifaro/Pareja-adicciones_zG9zFM2H.png",
    "date": "10 de Mayo, 2026",
    "publishedAt": "2026-05-10",
    "author": "Equipo Mi Faro",
    "category": "Vínculos y pareja"
  },
  {
    "id": "mi-pareja-consume-no-se-que-hacer-orientacion-valencia",
    "title": "Mi pareja consume y ya no sé qué hacer: señales de que es momento de pedir orientación",
    "excerpt": "Hay personas que no buscan ayuda para ellas. Buscan ayuda para su pareja. Y cuando llegan, descubren que también la necesitan ellas.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1779830060/mifaro/Terapia-de-pareja-adicciones_2yYThH37.png",
    "date": "26 de Mayo, 2026",
    "publishedAt": "2026-05-26",
    "author": "Ale Garcia",
    "category": "Adicciones y familia"
  },
  {
    "id": "mi-hijo-ha-cambiado-adolescencia-orientacion-valencia",
    "title": "Pedir orientación para un adolescente en Valencia: cuándo y cómo dar el primer paso",
    "excerpt": "La adolescencia cambia a los hijos. Eso es normal. Lo que no siempre es normal es el nivel de malestar que deja en la familia - y en el propio joven.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1779830156/mifaro/terapia-adolescentes-valencia_rF0Sx5zW.png",
    "date": "28 de Mayo, 2026",
    "publishedAt": "2026-05-28",
    "author": "Equipo Mi Faro",
    "category": "Familias y adolescentes"
  },
  {
    "id": "crisis-ansiedad-valencia",
    "title": "Crisis de ansiedad en Valencia: cuando el cuerpo entra en alerta",
    "excerpt": "Una crisis de ansiedad puede sentirse como si algo grave fuera a pasar. El cuerpo se acelera, la mente se asusta y todo parece urgente. Entender qué ocurre es el primer paso para no vivirlo en soledad.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1779830113/mifaro/Ansiedad-valencia_XvvV3C1q.jpg",
    "date": "08 de Junio, 2026",
    "publishedAt": "2026-06-08",
    "author": "Equipo Mi Faro",
    "category": "Ansiedad y malestar"
  },
  {
    "id": "soledad-no-elegida-adultos-valencia",
    "title": "Soledad no elegida: cuando te sientes solo aunque no estés solo",
    "excerpt": "Vivimos en la era más conectada de la historia. Y sin embargo, una de cada cinco personas en España se siente sola. No es una paradoja menor. Es una epidemia silenciosa que afecta más a los adultos jóvenes de lo que imaginamos.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto/v1780987326/mifaro/soledad-no-elegida-adultos-valencia-hero.png",
    "imageAlt": "Persona sentada en un banco de Valencia mirando al horizonte, luz de tarde, ciudad al fondo",
    "date": "9 de Junio, 2026",
    "publishedAt": "2026-06-09",
    "author": "Equipo Mi Faro",
    "category": "Salud mental y sociedad"
  },
  {
    "id": "ecoansiedad-dana-valencia",
    "title": "Ecoansiedad en Valencia: cuando el cielo gris vuelve a preocupar",
    "excerpt": "Hay experiencias emocionales que no necesitan dramatismo para ser tomadas en serio. Desde la DANA, muchas personas en Valencia describen una inquietud distinta ante la lluvia o las alertas meteorológicas. Ponerle nombre no resuelve todo, pero ayuda a comprender mejor lo que pasa.",
    "imageUrl": "https://res.cloudinary.com/dwv5ehc6e/image/upload/f_auto,q_auto,c_fill,ar_16:9,g_auto/v1781344717/mifaro/ecoansiedad-dana-valencia-1.png",
    "imageAlt": "Cielo nublado sobre tejados de Valencia, luz gris previa a la tormenta",
    "date": "13 de Junio, 2026",
    "publishedAt": "2026-06-13",
    "author": "Equipo Mi Faro",
    "category": "Salud mental y sociedad"
  },
  {
    "id": "por-que-cuesta-salir-relacion-toxica-valencia",
    "title": "¿Por qué cuesta tanto salir de una relación que hace daño?",
    "excerpt": "Sabes que esa relación te hace daño, y aun así, volver parece más fácil que marcharte. Te explicamos qué papel juegan el refuerzo intermitente y el vínculo traumático — y qué ayuda a romper el ciclo.",
    "imageUrl": "/por-que-cuesta-salir-relacion-toxica.jpg",
    "imagePosition": "object-[90%_50%]",
    "date": "26 de Julio, 2026",
    "publishedAt": "2026-07-26",
    "author": "Equipo Mi Faro",
    "category": "Vínculos y pareja"
  }
];
